"""
initialize constants which are going to use
"""
property_file = "config\knapsack.properties"
log_file = "logs\knapsack.log"
regex_pattern_english_alphabet = "[a-zA-Z]+$"
regex_pattern_digit = "\d+$"
regex_pattern_range = "\d+-\d+$"
regex_pattern_boolean = "(?i)true$|false$"
regex_pattern_decipher_side_choice = "(?i)^(r|a)$"
foreground_colorant_black = "\033[30m"
foreground_colorant_red = "\033[31m"
foreground_colorant_green = "\033[32m"
foreground_colorant_yellow = "\033[33m"
foreground_colorant_blue = "\033[34m"
background_colorant_black = "\033[40m"
background_colorant_red = "\033[41m"
background_colorant_green = "\033[42m"
background_colorant_yellow = "\033[43m"
background_colorant_blue = "\033[44m"
background_colorant_white = "\033[47m"
bold_attribute = "\033[1m"
attribute_default = "\033[0m"
terminal_delimiter = "\n*******************"
section_vector = "VectorSection"
section_parameters = "ParametersSection"
algorithm_brute_force = "BruteForce"
algorithm_totient = "Totient"
algorithm_back_tracking = "BackTracking"
structure_type_string = "String"
structure_type_boolean = "Boolean"
structure_type_int = "Int"
structure_type_float = "Float"
